Olympus dao/da oand policy contracts
NethermindEth/Forta-Agents pull request #106
Opened 2022-01-04 11:28 UTC by CeliktepeMurat

2022-01-04 13:06 UTC, e1Ru1o approved these changes

2022-01-04 13:06 UTC, e1Ru1o commented on OlympusDAO-Agent-Suit/DAOandPolicyContractAgents/src/agent.spec.ts
> +  it('should return `ChangedThreshol` event finding', async () => {
```suggestion
  it('should return `ChangedThreshold` event finding', async () => {
```

2022-01-04 13:06 UTC, e1Ru1o commented on OlympusDAO-Agent-Suit/DAOandPolicyContractAgents/package.json
> +    "bignumber.js": "^9.0.1",
remove this unused dependency and update the package-lock accordingly

2022-01-04 20:28 UTC, mauricio1802 requested changes

2022-01-04 20:28 UTC, mauricio1802 commented on OlympusDAO-Agent-Suit/DAOandPolicyContractAgents/src/agent.spec.ts
> +describe('high gas agent', () => {
Describe text looks wrong.

2022-01-07 14:12 UTC, mauricio1802 approved these changes

2022-01-07 14:13 UTC, merged