High Deposit/Withdrawals
NethermindEth/Forta-Agents pull request #109
Opened 2022-01-04 20:19 UTC by e1Ru1o

2022-01-04 21:12 UTC, mauricio1802 requested changes
Change PR destination to `@olympusDAO`

2022-01-04 21:12 UTC, mauricio1802 commented on OlympusDAO-Agent-Suit/DepositsAndWithdrawals/README.md
> +  - Type is always set to "suspicious" (mention any conditions where it could be something else)
Remove comments between `()`.

2022-01-04 21:12 UTC, mauricio1802 commented on OlympusDAO-Agent-Suit/DepositsAndWithdrawals/README.md
> +  - Type is always set to "suspicious" (mention any conditions where it could be something else)
Remove comments between ().

2022-01-06 13:43 UTC, CeliktepeMurat requested changes
Change destination of PR from `main`  to `@olympusDAO`

2022-01-06 13:43 UTC, CeliktepeMurat commented on OlympusDAO-Agent-Suit/DepositsAndWithdrawals/README.md
> +  - Fired when a high deposit ocur
typo -> "occurs"

2022-01-06 13:43 UTC, CeliktepeMurat commented on OlympusDAO-Agent-Suit/DepositsAndWithdrawals/README.md
> +  - Fired when a high withdrawal ocur
typo -> "occurs"

2022-01-07 11:53 UTC, CeliktepeMurat approved these changes

2022-01-07 14:24 UTC, mauricio1802 approved these changes

2022-01-07 14:25 UTC, merged