Calls to SetAdjustment
NethermindEth/Forta-Agents pull request #112
Opened 2022-01-05 16:10 UTC by mauricio1802

2022-01-05 16:20 UTC, e1Ru1o requested changes

2022-01-05 16:20 UTC, e1Ru1o commented on OlympusDAO-Agent-Suit/StakingContractSetAdjustment/src/agent.ts
> +    txEvent.filterFunction;
```suggestion
```

2022-01-05 16:20 UTC, e1Ru1o commented on OlympusDAO-Agent-Suit/StakingContractSetAdjustment/src/agent.ts
> +  handleTransaction: provideHandleTransaction(""),
I think you should use `STAKING_CONTRACT_ADDRESS` here.

2022-01-06 13:39 UTC, CeliktepeMurat approved these changes

2022-01-07 03:33 UTC, e1Ru1o approved these changes

2022-01-07 03:33 UTC, merged