@alpaca/liquidation alert
NethermindEth/Forta-Agents pull request #138
Opened 2022-01-28 21:03 UTC by RCantu92

`ALPACA-3` agent detects `Kill` event emissions from `Vault` contracts.
`ALPACA-4` agent detects `Kill` event emission from `Vault` contracts when `left` equals zero.

2022-02-01 03:03 UTC, mauricio1802 commented on Alpaca-Finance-Agents/Liquidation-Alert/src/agent.ts
> +): Finding[] => {
I think you shouldn't delegate the responsibility for deciding which alerts to emit to this function.

2022-02-02 23:43 UTC, mauricio1802 requested changes

2022-02-02 23:43 UTC, mauricio1802 commented on Alpaca-Finance-Agents/Liquidation-Alert/src/agent.ts
> +      for(let v = 0; v < addresses.length; v++) {
You have to remove this `for` loop. If you leave that for you would be checking if the address emitting the event is a relevant address `N` times, where `N` is the length of the `addresses` array. 
I think you can add one more address to the `TEST_VAULT_ADDRESSES` for checking what I am saying

2022-02-04 20:05 UTC, mauricio1802 approved these changes

2022-02-04 21:05 UTC, e1Ru1o requested changes

2022-02-04 21:05 UTC, e1Ru1o commented on Alpaca-Finance-Agents/Liquidation-Alert/src/agent.ts
> +        if(Number(killEvents[i].args["left"]) === 0) {
This seems safer to me:
```suggestion
        if(BigNumber.from(0).eq(killEvents[i].args["left"])) {
```
I am not sure that parsing to `Number` will be safe.

You should import `BigNumber` from `ethers`:
`import { BigNumber } from "ethers";`

2022-02-05 20:19 UTC, RCantu92 commented on Alpaca-Finance-Agents/Liquidation-Alert/README.md
> +    - `left`: What is returned to the target position's owner after liquidation execution.
That is true.

However, the other agent would also include it and perhaps including it in the one that confirms it is zero can display it for "peace of mind" for whoever sees it. Thoughts? I'm kind of leaning towards leaving it, especially if it doesn't hurt to include it.

2022-02-07 16:31 UTC, e1Ru1o commented on Alpaca-Finance-Agents/Liquidation-Alert/README.md
> +    - `left`: What is returned to the target position's owner after liquidation execution.
Keep it

2022-02-08 03:02 UTC, e1Ru1o approved these changes

2022-02-23 20:52 UTC, merged