@impossible/deposits withdraws on pairs
NethermindEth/Forta-Agents pull request #139
Opened 2022-02-01 00:15 UTC by e1Ru1o

2022-02-18 17:31 UTC, yasmine9 commented on Impossible-Agent-Suite/LargeDepositWithdrawOnPairs/src/findings.ts
> +
missing `protocol` in the finding, same for the ones on tests

2022-02-22 03:08 UTC, Kalzak requested changes

2022-02-23 03:00 UTC, Kalzak approved these changes

2022-02-23 17:09 UTC, yasmine9 approved these changes

2022-03-04 06:01 UTC, merged