@impossible/large deposits withdraws
NethermindEth/Forta-Agents pull request #147
Opened 2022-02-11 20:45 UTC by yasmine9

2022-02-11 22:11 UTC, e1Ru1o requested changes

2022-02-14 19:57 UTC, yasmine9 commented on Impossible-Agent-Suite/large-deposits-withdraws/src/large.sales.handler.ts
> +export const provideSaleHandler = async (
changed to `saleHandler`

2022-02-14 19:57 UTC, yasmine9 commented on Impossible-Agent-Suite/large-deposits-withdraws/src/large.staking.handler.ts
> +export const provideStakeHandler = async (
changed to `stakeHandler`

2022-02-14 19:57 UTC, yasmine9 commented on Impossible-Agent-Suite/large-deposits-withdraws/src/large.staking.handler.ts
> +    txEvent.blockNumber
addressed in the last commit

2022-02-14 19:58 UTC, yasmine9 commented on Impossible-Agent-Suite/large-deposits-withdraws/src/stake.fetcher.spec.ts
> +        //   trackId
was using the argument in an older version, comment removed in the last commit

2022-02-14 20:00 UTC, yasmine9 commented on Impossible-Agent-Suite/large-deposits-withdraws/src/agent.spec.ts
> +    const findings = await (await Promise.all(handlerCalls)).flat();
addressed in the last commit

2022-02-14 20:28 UTC, yasmine9 commented on Impossible-Agent-Suite/large-deposits-withdraws/src/sales.fetcher.ts
> +  private mock: boolean;
undefined logic removed

2022-02-14 20:49 UTC, e1Ru1o approved these changes
Nice work

2022-03-04 06:09 UTC, merged