@benqi/large mint burn
NethermindEth/Forta-Agents pull request #179
Opened 2022-03-21 11:03 UTC by yasmine9

# Agent name here

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] New Agent
- [ ] Fix an agent error
- [ ] Update an agent logic/test/documentation
- [ ] Code style update (formatting, renaming)
- [ ] Other (please describe):

## New Agent PR readiness

- [ ] `npm install` command works (i.e. package-lock is updated properly)
- [ ] The `name` and `description` fields of `package.json` describe the agent properly
- [ ] All the libraries listed in `package.json` are being used
- [ ] All the development libraries are in `devDependencies` section of `package.json`
- [ ] The agent README is updated
- [ ] The agent README sufficiently describes what the agent does
- [ ] All the alerts that the agent emits are listed in the README
- [ ] The txn/block examples listed in the README generate the expected findings
- [ ] Code is easy to follow and/or properly commented
- [ ] Agent contains tests
- [ ] All tests pass when running `npm test`
- [ ] Tests are not making real network calls (i.e. network interaction is properly mocked)
- [ ] Tests cover all the paths (i.e. negative & positive test cases)
- [ ] When the tests complete, no warning/errors are shown
- [ ] `npm start` works without errors when executed using a jsonRpcUrl for each of the networks specified in the README
- [ ] The code does what the README describes
- [ ] Network calls are properly being cached (if duplicated calls can occur)
- [ ] A performance review has been done (e.g. `Promise.all` is used whenever possible)
- [ ] The findings fields are filled out correctly
- [ ] Findings `protocol` is specified (if the agent is for a specific one)
- [ ] `metadata` of the findings contains all the information needed.
- [ ] The SDK methods are being used appropriately (e.g. `filterLog`, `filterFunction`, `getEthersProvider`)
- [ ] `ABI`s match the contracts used / `args` used from `LogDescriptions` exists in the `ABI`s
- [ ] The agent follows Forta recommended [best practices](https://docs.forta.network/en/latest/best-practices/)
- [ ] Agent can recover from failed error calls when they can fail (e.g. errors are being caught on calls that can fail)

## Comments (optional)

If there is some useful information or important note for reviewing/understanding this agent please describe it here.

2022-03-21 12:38 UTC, Kalzak requested changes

2022-03-21 12:38 UTC, Kalzak commented on Benqi-Agents/Large-Mint-Burn/package.json
> +  "devDependencies": {
`prettier` seems to be missing, please add it and run `npm run format`.

2022-03-21 12:42 UTC, Kalzak reviewed
Documentation recommendations

2022-03-21 12:42 UTC, Kalzak commented on Benqi-Agents/Large-Mint-Burn/README.md
> +There's no txs including large Mints/Burns on PGL contract. We have deployed a PoC contract to emit the monitored events. The agent behaviour can be verified with the following test transactions (Rop
```suggestion
There are no transactions including large Mints/Burns on PGL contract. We have deployed a PoC contract to emit the monitored events. The agent behaviour can be verified with the following test transactions (Ropsten):
```

2022-03-21 12:42 UTC, Kalzak commented on Benqi-Agents/Large-Mint-Burn/README.md
> +> note that `TESTNET_PGL_CONTRACT` should be used instead of `PGL_CONTRACT`.
We should mention where and how this should be changed in-case there are some people using this agent who aren't too familiar with Forta.

2022-03-21 12:42 UTC, Kalzak commented on Benqi-Agents/Large-Mint-Burn/README.md
> +- 0x212324e7e0909810cbf002414488a7d448a219f5a7e06d824e7b43925287b8bd (`Mint` with regulat amounts - no Finding generated).
```suggestion
- 0x212324e7e0909810cbf002414488a7d448a219f5a7e06d824e7b43925287b8bd (`Mint` with regular amounts - no Finding generated).
```

2022-03-21 12:42 UTC, Kalzak commented on Benqi-Agents/Large-Mint-Burn/README.md
> +- 0xb4f867b6558c371b19b3f16e43468287f0d91e8b156a0b54ff3f3b957fa25ce4 (`Burn` with large QI-WAVAX amounts- Finding generated).
```suggestion
- 0xb4f867b6558c371b19b3f16e43468287f0d91e8b156a0b54ff3f3b957fa25ce4 (`Burn` with large QI-WAVAX amounts - Finding generated).
```

2022-03-21 12:42 UTC, Kalzak commented on Benqi-Agents/Large-Mint-Burn/README.md
> +> note that `TESTNET_PGL_CONTRACT` should be used instead of `PGL_CONTRACT`.
Something simple like mentioning to change the inputs to `provideHandleTransaction` in the default exports in `agent.ts` should suffice.

2022-03-22 11:59 UTC, 0xtaf commented
.gitignore, .prettierrc and .dockerignore files are missing.

2022-03-23 02:24 UTC, e1Ru1o commented on Benqi-Agents/Large-Mint-Burn/src/agent.spec.ts
> +});
Is this supposed to be here?

2022-03-23 02:37 UTC, e1Ru1o commented on Benqi-Agents/Large-Mint-Burn/src/agent.ts
> +    new ReservesFetcher(getEthersProvider(), PGL_CONTRACT)
would be nice to use in the agent logic the same pglAddress used in the Fetcher (i.e `fetcher.pglAddress`) two avoid passing twice the address here

2022-03-24 23:23 UTC, e1Ru1o approved these changes

2022-03-25 17:57 UTC, RCantu92 approved these changes
Just a couple of general comments:

I think if we have a test that generates multiple Findings, it is probably unnecessary to then write a test whose only goal is to confirm multiple Findings are generated. (e.g. `"should return a finding when both QI-WAVAX amounts are above the threshold"` and `should return multiple findings`.)

Secondly, it would probably be better to deploy to the mainnet's own testnet. In this case deploying the PoC contract to the Avalanche testnet rather than Ropsten, which was used. However, this has already been discussed, and I think this will be implemented going forward.

2022-03-25 18:36 UTC, Kalzak approved these changes

2022-03-25 19:30 UTC, merged