MakerDAO Governance-Module Update
NethermindEth/Forta-Agents pull request #186
Opened 2022-04-13 14:31 UTC by 0xtaf

# Agent name here

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] New Agent
- [ ] Fix an agent error
- [x] Update an agent logic/test/documentation
- [ ] Code style update (formatting, renaming)
- [ ] Other (please describe):

## New Agent PR readiness

- [ ] `npm install` command works (i.e. package-lock is updated properly)
- [ ] The `name` and `description` fields of `package.json` describe the agent properly
- [ ] All the libraries listed in `package.json` are being used
- [ ] All the development libraries are in `devDependencies` section of `package.json`
- [ ] The agent README is updated
- [ ] The agent README sufficiently describes what the agent does
- [ ] All the alerts that the agent emits are listed in the README
- [ ] The txn/block examples listed in the README generate the expected findings
- [ ] Code is easy to follow and/or properly commented
- [ ] Agent contains tests
- [ ] All tests pass when running `npm test`
- [ ] Tests are not making real network calls (i.e. network interaction is properly mocked)
- [ ] Tests cover all the paths (i.e. negative & positive test cases)
- [ ] When the tests complete, no warning/errors are shown
- [ ] `npm start` works without errors when executed using a jsonRpcUrl for each of the networks specified in the README
- [ ] The code does what the README describes
- [ ] Network calls are properly being cached (if duplicated calls can occur)
- [ ] A performance review has been done (e.g. `Promise.all` is used whenever possible)
- [ ] The findings fields are filled out correctly
- [ ] Findings `protocol` is specified (if the agent is for a specific one)
- [ ] `metadata` of the findings contains all the information needed.
- [ ] The SDK methods are being used appropriately (e.g. `filterLog`, `filterFunction`, `getEthersProvider`)
- [ ] `ABI`s match the contracts used / `args` used from `LogDescriptions` exists in the `ABI`s
- [ ] The agent follows Forta recommended [best practices](https://docs.forta.network/en/latest/best-practices/)
- [ ] Agent can recover from failed error calls when they can fail (e.g. errors are being caught on calls that can fail)

## Comments (optional)

If there is some useful information or important note for reviewing/understanding this agent please describe it here.

2022-04-14 14:16 UTC, yasmine9 commented on Maker-Agents-Suit-Module/Governance-Module/package.json
> +  "version": "0.0.2",
Not sure if we should move to version 0.0.2 while the first one wasn't even deployed

2022-04-14 18:06 UTC, RCantu92 reviewed
Overall, good work. Left some minor comments

2022-04-14 18:37 UTC, 0xtaf commented on Maker-Agents-Suit-Module/Governance-Module/src/agent.ts
> +  lifterManager: AddressManager
they both have the same Interface of AddressManager so it's not a type but it's an interface which has its isKnownAddress method that's used by both spellsManager and lifterManager

2022-04-14 19:09 UTC, RCantu92 approved these changes
LGTM 🚀

2022-04-18 15:01 UTC, yasmine9 requested changes

2022-04-18 15:08 UTC, RCantu92 approved these changes
Left one minor comment, but overall LGTM 🚀

2022-04-18 15:20 UTC, 0xtaf commented on Maker-Agents/Governance-Module/src/agent.ts
> +    // Listen to UpdateAddress event & Update the chief contract.
great catch! I'll delete it as a param.

2022-04-18 16:08 UTC, yasmine9 approved these changes
Updates LGTM ✅

2022-04-18 17:48 UTC, merged