ESM Agent
NethermindEth/Forta-Agents pull request #188
Opened 2022-04-13 17:47 UTC by RCantu92

# Agent name here

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] New Agent
- [ ] Fix an agent error
- [x] Update an agent logic/test/documentation
- [ ] Code style update (formatting, renaming)
- [ ] Other (please describe):

## New Agent PR readiness

- [x] `npm install` command works (i.e. package-lock is updated properly)
- [x] The `name` and `description` fields of `package.json` describe the agent properly
- [x] All the libraries listed in `package.json` are being used
- [x] All the development libraries are in `devDependencies` section of `package.json`
- [ ] The agent README is updated
- [ ] The agent README sufficiently describes what the agent does
- [ ] All the alerts that the agent emits are listed in the README
- [ ] The txn/block examples listed in the README generate the expected findings
- [ ] Code is easy to follow and/or properly commented
- [x] Agent contains tests
- [ ] All tests pass when running `npm test`
- [ ] Tests are not making real network calls (i.e. network interaction is properly mocked)
- [x] Tests cover all the paths (i.e. negative & positive test cases)
- [ ] When the tests complete, no warning/errors are shown
- [ ] `npm start` works without errors when executed using a jsonRpcUrl for each of the networks specified in the README
- [x] The code does what the README describes
- [ ] Network calls are properly being cached (if duplicated calls can occur)
- [ ] A performance review has been done (e.g. `Promise.all` is used whenever possible)
- [x] The findings fields are filled out correctly
- [x] Findings `protocol` is specified (if the agent is for a specific one)
- [x] `metadata` of the findings contains all the information needed.
- [x] The SDK methods are being used appropriately (e.g. `filterLog`, `filterFunction`, `getEthersProvider`)
- [ ] `ABI`s match the contracts used / `args` used from `LogDescriptions` exists in the `ABI`s
- [ ] The agent follows Forta recommended [best practices](https://docs.forta.network/en/latest/best-practices/)
- [ ] Agent can recover from failed error calls when they can fail (e.g. errors are being caught on calls that can fail)

## Comments (optional)
- Update `forta-agent` and `forta-agent-tools` in `package.json`

2022-04-14 11:46 UTC, yasmine9 commented on Maker-Agents-Suit-Module/ESMAgent/package.json
> +    "forta-agent-tools": "2.0.5"
Please move `forta-agent-tools` to devDependencies

2022-04-14 12:16 UTC, 0xtaf requested changes
Please update `package-lock.json` by removing `node_modules` and `package-lock.json` together, and then doing `npm install` again. because I encountered a breaker related to usage of Interfaces. the older version of ethers and @ethersproject in this project are 6 months - 2 years older respectively.

2022-04-14 14:32 UTC, yasmine9 commented on Maker-Agents-Suit-Module/ESMAgent/package.json
> +    "forta-agent-tools": "2.0.5"
Oh I missed that it's used in the logic. Yes, you're totally right.

2022-04-14 14:50 UTC, yasmine9 approved these changes
The bot updates LGTM

2022-04-14 16:30 UTC, 0xtaf requested changes

2022-04-14 16:30 UTC, 0xtaf commented on Maker-Agents-Suit-Module/ESMAgent/src/agent.ts
> +const MakerDAO_ESM_CONTRACT = "0x29cfbd381043d00a98fd9904a431015fef07af2f";
according to the [latest release](https://chainlog.makerdao.com/api/mainnet/active.json), ESM address seems to be different ("MCD_ESM": "0x09e05ff6142f2f9de8b6b65855a1d56b6cfe4c58"). 
this one belongs to [the older version](https://changelog.makerdao.com/releases/mainnet/1.9.10/contracts.json)
ESM in `agent.spec.ts` and `README.md` also needs to be changed.

example tx in the README.md becomes invalid after changing the ESM address.

2022-04-14 16:30 UTC, 0xtaf commented on Maker-Agents-Suit-Module/ESMAgent/src/agent.ts
> +const MakerDAO_ESM_CONTRACT = "0x29cfbd381043d00a98fd9904a431015fef07af2f";
according to the [latest release](https://chainlog.makerdao.com/api/mainnet/active.json), ESM address seems to be different ("MCD_ESM": "0x09e05ff6142f2f9de8b6b65855a1d56b6cfe4c58"). 
this one belongs to [the older version](https://changelog.makerdao.com/releases/mainnet/1.9.10/contracts.json)

2022-04-14 19:05 UTC, 0xtaf approved these changes

2022-04-15 09:29 UTC, Vxatz commented on Maker-Agents/ESMAgent/src/join.event.spec.ts
> +  it("should returns a finding if condition is met", async () => {
```suggestion
  it("should return a finding if condition is met", async () => {
```

2022-04-15 09:35 UTC, Vxatz commented on Maker-Agents/ESMAgent/README.md
> +  - Severity is always set to "medium" .
```suggestion
  - Severity is always set to "Medium" .
```

2022-04-15 09:35 UTC, Vxatz commented on Maker-Agents/ESMAgent/README.md
> +  - Type is always set to "suspicious".
```suggestion
  - Type is always set to "Suspicious".
```

2022-04-15 09:35 UTC, Vxatz commented on Maker-Agents/ESMAgent/README.md
> +  - Severity is always set to "critical".
```suggestion
  - Severity is always set to "Critical".
```

2022-04-15 09:35 UTC, Vxatz commented on Maker-Agents/ESMAgent/README.md
> +  - Type is always set to "suspicious".
```suggestion
  - Type is always set to "Suspicious".
```

2022-04-15 09:49 UTC, Vxatz commented on Maker-Agents/ESMAgent/src/fire.event.spec.ts
> +  it("should return empty finding cause bad ADDRESS", async () => {
```suggestion
  it("should return empty finding because of bad address", async () => {
```

2022-04-15 09:50 UTC, Vxatz commented on Maker-Agents/ESMAgent/src/fire.event.spec.ts
> +  it("should return empty finding cause bad SIGNATURE", async () => {
```suggestion
  it("should return empty finding because of bad signature", async () => {
```

2022-04-15 09:51 UTC, Vxatz commented on Maker-Agents/ESMAgent/src/fire.event.spec.ts
> +  it("should return empty finding cause bad SIGNATURE and bad ADDRESS", async () => {
```suggestion
  it("should return empty finding because of bad signature and bad address", async () => {
```

2022-04-15 09:54 UTC, Vxatz commented on Maker-Agents/ESMAgent/src/fire.event.spec.ts
> +  it("should return empty finding cause bad SIGNATURE and bad ADDRESS", async () => {
Also, this test is probably redundant.

2022-04-15 20:31 UTC, Vxatz commented on Maker-Agents/ESMAgent/src/agent.ts
> +    console.log("made it here 01");
```suggestion
    
```

2022-04-15 20:31 UTC, Vxatz commented on Maker-Agents/ESMAgent/src/agent.ts
> +    console.log("made it here 02");
```suggestion
    
```

2022-04-18 14:57 UTC, 0xtaf requested changes

2022-04-18 14:57 UTC, 0xtaf commented on Maker-Agents/ESMAgent/src/agent.ts
>    intialize: provideInitialize(MakerDAO_CHANGELOG_ADDRESS, ESM_CONTRACT_BYTES, getEthersProvider()),
typo here: it should be "initialize:". otherwise it wouldn't initialize it.

2022-04-18 15:20 UTC, yasmine9 requested changes
One note needs to be checked and fixed if it makes sense. Other than that, LGTM ✅

2022-04-18 15:20 UTC, yasmine9 commented on Maker-Agents/ESMAgent/src/agent.ts
> +
The handler parameters are passed before the `initialize` function is executed and the `esmAddress` is initialized. Therefore, printing `esmAddress` value here will always give the empty string value. Please check that

2022-04-18 17:14 UTC, yasmine9 approved these changes

2022-04-18 17:38 UTC, 0xtaf approved these changes

2022-04-18 19:27 UTC, merged