TJ25 - Reentrancy Transfers
NethermindEth/Forta-Agents pull request #255
Opened 2022-06-01 18:10 UTC by yasmine9

# Reentrancy Transfers

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] New Bot
- [ ] Fix a bot error
- [ ] Update a bot logic/test/documentation
- [ ] Code style update (formatting, renaming)
- [ ] Other (please describe):

## New Bot PR readiness

- [x] `npm install` command works (i.e. package-lock is updated properly)
- [x] The `name` and `description` fields of `package.json` describe the bot properly
- [x] All the libraries listed in `package.json` are being used
- [x] All the development libraries are in `devDependencies` section of `package.json`
- [x] The bot README is updated
- [x] The bot README sufficiently describes what the bot does
- [x] All the alerts that the bot emits are listed in the README
- [x] The txn/block examples listed in the README generate the expected findings
- [x] Code is easy to follow and/or properly commented
- [x] Bot contains tests
- [x] All tests pass when running `npm test`
- [x] Tests are not making real network calls (i.e. network interaction is properly mocked)
- [x] Tests cover all the paths (i.e. negative & positive test cases)
- [x] When the tests complete, no warning/errors are shown
- [x] `npm start` works without errors when executed using a jsonRpcUrl for each of the networks specified in the README
- [x] The networks specified in the README and the networks are listed in the `package.json` are the same
- [x] The code does what the README describes
- [x] Network calls are properly being cached (if duplicated calls can occur)
- [ ] A performance review has been done (e.g. `Promise.all` is used whenever possible)
- [x] The findings fields are filled out correctly
- [x] Findings `protocol` is specified (if the bot is for a specific one)
- [x] `metadata` of the findings contains all the information needed.
- [x] The SDK methods are being used appropriately (e.g. `filterLog`, `filterFunction`, `getEthersProvider`)
- [ ] `ABI`s match the contracts used / `args` used from `LogDescriptions` exists in the `ABI`s
- [x] The bot follows Forta recommended [best practices](https://docs.forta.network/en/latest/best-practices/)
- [x] Bot can recover from failed error calls when they can fail (e.g. errors are being caught on calls that can fail)
- [x] `repository` is added in the `package.json`

2022-06-02 16:30 UTC, yasmine9 commented on TraderJoe-Bots/Re-entrancy-Transfers/src/agent.ts
> +    if (sighashes.length > 0) {
Self reviewing.. 

Maybe we can get ride of `filterFunction` usage and just parse manually traces for each transactionEvent. The only optimisation here is avoiding to do that when there's no call, ie `sighashes.length == 0`. 


The problem is that `filterFunction` is already looping over traces, to only decide if there's a call or not. Then we are looping over them again to check for re-entrancy, which is making the bot heavier. 

The alternative solution is removing the selected lines of this comment, and replacing `sighashes` with an array of all monitored functions selectors.  Thoughts on what is more optimized?

2022-06-02 16:30 UTC, yasmine9 commented on TraderJoe-Bots/Re-entrancy-Transfers/src/agent.ts
> +    if (sighashes.length > 0) {
Self reviewing.. 

Maybe we can get ride of `filterFunction` usage and just parse manually traces for each transactionEvent. The only optimisation here is avoiding to do that when there's no call, ie `sighashes.length == 0`. 


The problem is that `filterFunction` is already looping over traces, to only decide if there's a call or not. Then we are looping over them again to check for re-entrancy, which is making the bot heavier. 

The alternative solution is removing the selected lines of this comment, and replacing `sighashes` with an array of all monitored functions selectors.  Thoughts on what is more optimized?

2022-06-05 20:39 UTC, RCantu92 reviewed
Looks pretty good to me. Just some minor comments.

2022-06-05 20:39 UTC, RCantu92 commented on TraderJoe-Bots/Re-entrancy-Transfers/README.md
> +    - `reEntrantCall`: selector of the function that was called in the re-entrancy case.
```suggestion
  - Metadata contains:
    - `from`: the address source making the second call to the contract.
    - `initialCall`: selector of the function that was initially called.
    - `entrancyFrom: ....
    - `reEntrantCall`: selector of the function that was called in the re-entrancy case.
```
Missing `entrancyFrom` property on `metadata` object.

2022-06-05 20:39 UTC, RCantu92 commented on TraderJoe-Bots/Re-entrancy-Transfers/src/agent.spec.ts
> +    const txEvent: TransactionEvent = createTransactionEvent({
Any particular reason to use `createTransactionEvent` over `TestTransactionEvent.addTrace()` from the `GAM`? Just curious.

2022-06-05 20:40 UTC, RCantu92 requested changes
The provided test data transactions on Kovan did not generate findings for me. I updated my `forta.config` to confirm it was on Kovan, and it did not fix the issue.

2022-06-05 20:40 UTC, RCantu92 commented on TraderJoe-Bots/Re-entrancy-Transfers/README.md
> +- 0x34103cfe0617268c77489a901beca99e2e9beb338f97544567ff8d3993df9ee7 (reentrancy on `TestMarket`).
Transactions aren't generating findings for me.

2022-06-06 07:57 UTC, yasmine9 commented on TraderJoe-Bots/Re-entrancy-Transfers/README.md
> +- 0x34103cfe0617268c77489a901beca99e2e9beb338f97544567ff8d3993df9ee7 (reentrancy on `TestMarket`).
I tested again and it is still generating findings for me. Please check if your endpoint is the one supporting traces.

2022-06-06 08:06 UTC, yasmine9 commented on TraderJoe-Bots/Re-entrancy-Transfers/src/agent.spec.ts
> +    const txEvent: TransactionEvent = createTransactionEvent({
That's because the `addTrace` from `GAM` doesn't support the `traceAddress` field, which is used in our logic.

2022-06-06 18:07 UTC, RCantu92 approved these changes
LGTM. 🚀 

Good job with updating the findings to use the function ABI rather than the signature. 👌

2022-06-09 20:39 UTC, e1Ru1o approved these changes

2022-06-09 20:39 UTC, e1Ru1o commented on TraderJoe-Bots/Re-entrancy-Transfers/src/agent.spec.ts
> +    reEtrantCall: string
```suggestion
    reentrancyFrom: string,
    initialCall: string,
    reEntrantCall: string
```
I would even use `reentrant` as a word, I mean in the last param I would not use that capital E

2022-06-09 20:39 UTC, e1Ru1o commented on TraderJoe-Bots/Re-entrancy-Transfers/src/agent.spec.ts
> +        entrancyFrom: rentrancyFrom, // the contract re-entring our contract.
```suggestion
        entrancyFrom: rentrancyFrom, // the contract re-entering our contract.
```
please check for typos related to reentrancy.

Additionally I will not say `our`

2022-06-10 07:51 UTC, yasmine9 commented on TraderJoe-Bots/Re-entrancy-Transfers/src/network.ts
> +    this.moneyMaker = "";
In fact, the problem happens only when the address is used to initialize a Contract to make a network call. In this bot, only `joeTroller` is used to fetch markets, and this one is initialized to the zero address inside `markets.fetcher.ts`.

But I think it's a good practice to always use zero address, updating the bot based on that.

2022-06-10 09:36 UTC, yasmine9 commented on TraderJoe-Bots/Re-entrancy-Transfers/src/utils.ts
> +export const FUNCTIONS_IFACE = new Interface(Array.from(FUNCTIONS_MAP.values()));
Yeah I totally agree, that's a much cleaner and dynamic way to do it. Thanks for the suggestion!

2022-06-10 11:57 UTC, e1Ru1o commented on TraderJoe-Bots/Re-entrancy-Transfers/src/finding.ts
> +        : reEtrantCall,
```suggestion
        : reentrantCall,
```
still a typo here

2022-06-10 11:57 UTC, e1Ru1o commented on TraderJoe-Bots/Re-entrancy-Transfers/src/utils.ts
> +    FUNCTIONS_IFACE.getSighash(FUNCTIONS_IFACE.getFunction(fragment.slice(9))),
```suggestion
    FUNCTIONS_IFACE.getSighash(FUNCTIONS_IFACE.getFunction(fragment)),
```
Why `slice(9)` fragment is the signature, not a selector or hash

2022-06-10 12:40 UTC, merged