CAKE-03
NethermindEth/Forta-Agents pull request #291
Opened 2022-06-27 12:26 UTC by sprtd

#  Large Liquidity Pool Deposit/Withdrawal Bot

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] New Bot
- [ ] Fix a bot error
- [ ] Update a bot logic/test/documentation
- [ ] Code style update (formatting, renaming)
- [ ] Other (please describe):

## New Bot PR readiness

- [x] `npm install` command works (i.e. package-lock is updated properly)
- [x] The `name` and `description` fields of `package.json` describe the bot properly
- [x] All the libraries listed in `package.json` are being used
- [x] All the development libraries are in `devDependencies` section of `package.json`
- [x] The bot README is updated
- [x] The bot README sufficiently describes what the bot does
- [x] All the alerts that the bot emits are listed in the README
- [x] The txn/block examples listed in the README generate the expected findings
- [x] Code is easy to follow and/or properly commented
- [x] Bot contains tests
- [x] All tests pass when running `npm test`
- [x] Tests are not making real network calls (i.e. network interaction is properly mocked)
- [x] Tests cover all the paths (i.e. negative & positive test cases)
- [x] When the tests complete, no warning/errors are shown
- [x] `npm start` works without errors when executed using a jsonRpcUrl for each of the networks specified in the README
- [x] The networks specified in the README and the networks are listed in the `package.json` are the same
- [x] The code does what the README describes
- [ ] Network calls are properly being cached (if duplicated calls can occur)
- [x] A performance review has been done (e.g. `Promise.all` is used whenever possible)
- [x] The findings fields are filled out correctly
- [x] Findings `protocol` is specified (if the bot is for a specific one)
- [x] `metadata` of the findings contains all the information needed.
- [x] The SDK methods are being used appropriately (e.g. `filterLog`, `filterFunction`, `getEthersProvider`)
- [x] `ABI`s match the contracts used / `args` used from `LogDescriptions` exists in the `ABI`s
- [x] The bot follows Forta recommended [best practices](https://docs.forta.network/en/latest/best-practices/)
- [x] Bot can recover from failed error calls when they can fail (e.g. errors are being caught on calls that can fail)
- [x] `repository` is added in the `package.json`

## Comments (optional)

If there is some useful information or important note for reviewing/understanding this bot please describe it here.

2022-06-27 17:52 UTC, Vxatz requested changes

2022-06-27 17:52 UTC, Vxatz commented on PancakeSwap-Bots/Large-LP-Deposit-Withdrawal/README.md
> +The agent behaviour can be verified with the following transactions:
```suggestion
The bot behaviour can be verified with the following transactions:
```

2022-06-27 17:52 UTC, Vxatz commented on PancakeSwap-Bots/Large-LP-Deposit-Withdrawal/package.json
> +    "forta-agent": "^0.1.7",
```suggestion
    "forta-agent": "^0.1.8",
```

Please use the updated version as it doesn't have the chanId issues

2022-06-27 17:52 UTC, Vxatz commented on PancakeSwap-Bots/Large-LP-Deposit-Withdrawal/src/agent.ts
> +        let token1: string = tokenA < tokenB ? tokenB : tokenA;
Actually, you don't need these as the fetcher already returns token0, token1, not tokenA, tokenB

2022-06-27 17:52 UTC, Vxatz commented on PancakeSwap-Bots/Large-LP-Deposit-Withdrawal/src/agent.ts
> +            totalSupply.gt(poolSupplyThreshold) &&
```suggestion
            totalSupply.gt(poolSupplyThreshold) &&
```

This is a nice addition, but it should be declared more clearly in the README both in the Description and in the Alerts section

+This requires an extra test

2022-06-27 17:52 UTC, Vxatz commented on PancakeSwap-Bots/Large-LP-Deposit-Withdrawal/src/finding.ts
> +      description: `${log.name} event with large amounts emitted from Pancakeswap pool`,
```suggestion
      description: `${log.name} event with large amounts emitted from a Pancakeswap pool`,
```

2022-06-27 17:52 UTC, Vxatz commented on PancakeSwap-Bots/Large-LP-Deposit-Withdrawal/src/finding.ts
> +      description: `${log.name} event with large amount emitted from an Pancakeswap pool`,
```suggestion
      description: `${log.name} event with large amounts emitted from a Pancakeswap pool`,
```

Just keeping consistency between the two descriptions.

2022-06-30 06:44 UTC, Vxatz approved these changes
Approved, as there are only small suggestions left!

2022-06-30 06:44 UTC, Vxatz commented on PancakeSwap-Bots/Large-LP-Deposit-Withdrawal/README.md
> +  - Fired when large liquidity is deposited to a Pancakeswap pool as `Mint` event is emitted with a `totalSuppply` that exceeds the pool's `poolSupplyThreshold` and `amount0`/`amount1` that exceeds `
```suggestion
- CAKE-3-1
  - Fired when large liquidity is deposited to a Pancakeswap pool as `Mint` event is emitted with a `totalSuppply` that exceeds the pool's `poolSupplyThreshold` and `amount0`/`amount1` that exceeds `token0`/`token1` `thresholdPercentage`
```

(just removing the space)

2022-06-30 06:44 UTC, Vxatz commented on PancakeSwap-Bots/Large-LP-Deposit-Withdrawal/README.md
> +  - Type is always set to "Suspicious"
```suggestion
- CAKE-3-2
  - Fired when large liquidity is withdrawn from a Pancakeswap pool as `Burn` event is emitted with a `totalSuppply` that exceeds the pool's `poolSupplyThreshold` threshold and `amount0`/`amount1` that exceeds `token0`/`token1` `thresholdPercentage`
  - Severity is always set to "Info"
  - Type is always set to "Info"
```

2022-06-30 06:44 UTC, Vxatz commented on PancakeSwap-Bots/Large-LP-Deposit-Withdrawal/package.json
> +    "forta-agent-tools": "^2.2.1",
```suggestion
    "forta-agent-tools": "^2.2.2",
```

Please 1) delete package-lock.json 2) change this to `^2.2.2` 3) run `npm install` and 4) push

2022-07-08 12:12 UTC, e1Ru1o approved these changes

2022-07-08 12:12 UTC, merged