CAKE04 - Large LP Token Deposit/Withdrawal
NethermindEth/Forta-Agents pull request #296
Opened 2022-06-29 12:16 UTC by thamsuppp

# CAKE04 - Large LP Token Deposit/Withdrawal

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ x ] New Bot
- [ ] Fix a bot error
- [ ] Update a bot logic/test/documentation
- [ ] Code style update (formatting, renaming)
- [ ] Other (please describe):

## New Bot PR readiness

- [ ] `npm install` command works (i.e. package-lock is updated properly)
- [ ] The `name` and `description` fields of `package.json` describe the bot properly
- [ ] All the libraries listed in `package.json` are being used
- [ ] All the development libraries are in `devDependencies` section of `package.json`
- [ ] The bot README is updated
- [ ] The bot README sufficiently describes what the bot does
- [ ] All the alerts that the bot emits are listed in the README
- [ ] The txn/block examples listed in the README generate the expected findings
- [ ] Code is easy to follow and/or properly commented
- [ ] Bot contains tests
- [ ] All tests pass when running `npm test`
- [ ] Tests are not making real network calls (i.e. network interaction is properly mocked)
- [ ] Tests cover all the paths (i.e. negative & positive test cases)
- [ ] When the tests complete, no warning/errors are shown
- [ ] `npm start` works without errors when executed using a jsonRpcUrl for each of the networks specified in the README
- [ ] The networks specified in the README and the networks are listed in the `package.json` are the same
- [ ] The code does what the README describes
- [ ] Network calls are properly being cached (if duplicated calls can occur)
- [ ] A performance review has been done (e.g. `Promise.all` is used whenever possible)
- [ ] The findings fields are filled out correctly
- [ ] Findings `protocol` is specified (if the bot is for a specific one)
- [ ] `metadata` of the findings contains all the information needed.
- [ ] The SDK methods are being used appropriately (e.g. `filterLog`, `filterFunction`, `getEthersProvider`)
- [ ] `ABI`s match the contracts used / `args` used from `LogDescriptions` exists in the `ABI`s
- [ ] The bot follows Forta recommended [best practices](https://docs.forta.network/en/latest/best-practices/)
- [ ] Bot can recover from failed error calls when they can fail (e.g. errors are being caught on calls that can fail)
- [ ] `repository` is added in the `package.json`

## Comments (optional)

If there is some useful information or important note for reviewing/understanding this bot please describe it here.

2022-06-29 16:44 UTC, Vxatz reviewed
Some notes:

- I'm not sure why you're using the `V2` instead of `V1` or both (is anything relevant mentioned in the research?)
- `EmergencyWithdraw`s are not currently checked.
- You can create a separate file fetcher class for all the network calls (where you can also use `lru-cache`), you may have a look in some of our other bots that use this.
- You may pass the MasterChef address as a parameter in `provideHandleTransaction`, in order to use a mockAddress while testing.
- You can add one test that in which multiple findings are created in each "describe"

2022-06-29 16:46 UTC, Vxatz commented on Pancakeswap-Agents/LargeLPTokenDepositWithdraw/README.md
> +- CAKE-1
```suggestion
- CAKE-4-1
```

2022-06-30 14:20 UTC, e1Ru1o submitted a review, later dismissed

2022-06-30 14:20 UTC, e1Ru1o commented on Pancakeswap-Agents/LargeLPTokenDepositWithdraw/README.md
> +This agent detects large LP Token Deposit/Withdraw on Pancakeswap
```suggestion
This bot detects large LP Token Deposit/Withdraw on Pancakeswap
```
Please change all the `agent` mentions to bot

2022-06-30 14:20 UTC, e1Ru1o commented on Pancakeswap-Agents/LargeLPTokenDepositWithdraw/src/agent.ts
> +        MASTERCHEF_ADDRESS
Here is better to use an address passed as a parameter instead of a global one. That will allow you to use a different one in the tests.

2022-06-30 14:20 UTC, e1Ru1o commented on Pancakeswap-Agents/LargeLPTokenDepositWithdraw/src/agent.spec.ts
> +})
Missing tests where multiple findings are detected

2022-07-06 18:31 UTC, Vxatz reviewed
- Please add the dashes in the folder name and change the directory in the package.json accordingly
- The `.prettierrc` needs to be moved inside the bot's folder (I didn't make this clear)
- A test with multiple findings is missing in the static threshold case + a test in the `EmergencyWithdraw` case (dynamic)
- While testing, it would be better practice to use a `MOCK_MASTERCHEF_ADDRESS` instead of using the real one 
- As the provider calls are 2-3, I still tend to believe that it would be cleaner to use a separate fetcher

2022-07-06 18:31 UTC, Vxatz commented on Pancakeswap-Agents/LargeLPTokenDepositWithdraw/src/agent.spec.ts
> +  balance: ethers.BigNumber,
```suggestion
  balance: BigNumber,
```
"ethers" is not needed as you're importing BigNumber directly (this applies to all the other occurrences too)

2022-07-06 18:31 UTC, Vxatz commented on Pancakeswap-Agents/LargeLPTokenDepositWithdraw/src/agent.spec.ts
> +}
You can separate these two calls, as in the Static mode you don't need to call `balanceOf`

2022-07-06 18:31 UTC, Vxatz commented on Pancakeswap-Agents/LargeLPTokenDepositWithdraw/src/agent.spec.ts
> +      // Create test transaction with the deposit event
```suggestion
      // Create test transaction with the withdraw event
```

2022-07-06 18:31 UTC, Vxatz commented on Pancakeswap-Agents/LargeLPTokenDepositWithdraw/src/agent.spec.ts
> +      // Add Deposit event
```suggestion
      // Add Withdraw event
```

2022-07-06 18:31 UTC, Vxatz commented on Pancakeswap-Agents/LargeLPTokenDepositWithdraw/src/agent.spec.ts
> +      // Create test transaction with the deposit event
```suggestion
      // Create test transaction with the EmegencyWithdraw event
```

2022-07-06 18:31 UTC, Vxatz commented on Pancakeswap-Agents/LargeLPTokenDepositWithdraw/src/agent.spec.ts
> +      // Add Deposit event
```suggestion
      // Add EmergencyWithdraw event
```

2022-07-06 18:31 UTC, Vxatz commented on Pancakeswap-Agents/LargeLPTokenDepositWithdraw/src/agent.spec.ts
> +      // Create test transaction with the deposit event
```suggestion
      // Create test transaction with the EmergencyWithdraw event
```

2022-07-06 18:31 UTC, Vxatz commented on Pancakeswap-Agents/LargeLPTokenDepositWithdraw/src/agent.spec.ts
> +      // Create test transaction with the deposit event
```suggestion
      // Add Withdraw event
      const testSpender: string = createAddress("0x9");
      const withdrawLog = MASTERCHEF_INTERFACE.encodeEventLog(MASTERCHEF_INTERFACE.getEvent("Withdraw"), [
        testSpender,
        20,
        BigNumber.from("3000000000000000000"), // 3
      ]);
      // Create test transaction with the withdraw event
```

2022-07-06 18:31 UTC, Vxatz commented on Pancakeswap-Agents/LargeLPTokenDepositWithdraw/src/agent.spec.ts
> +      // Create test transaction with the deposit event
```suggestion
      // Add Withdraw event
      const testSpender: string = createAddress("0x9");
      const withdrawLog = MASTERCHEF_INTERFACE.encodeEventLog(MASTERCHEF_INTERFACE.getEvent("Withdraw"), [
        testSpender,
        20,
        BigNumber.from("2400000000000000000"), // 2.4
      ]);
      // Create test transaction with the withdraw event
```

2022-07-21 16:03 UTC, Vxatz commented
Hey @thamsuppp, please let me know when the PR is ready for a re-review

2022-07-22 10:45 UTC, Vxatz requested changes
A couple things left:

- You should add some info/instructions of the bot in the README. (That it supports both Static and Dynamic modes and where the mode and the thresholds can be configured)
- LRU-Cache can be added to the fetchers (more info [here](https://www.notion.so/nethermind/Advanced-agents-development-wip-019f0fe5ef4c4e378b4a62bcf1f36b18))
- Separate `.spec.ts` should be created in order to test the fetchers

2022-07-22 10:45 UTC, Vxatz commented on Pancakeswap-Agents/Large-LP-Token-Deposit-Withdraw/src/findings.ts
> +      token: tokenName,
I think that all LP Tokens are named "Pancake LPs" and if this is the case, then there is no reason to fetch the `tokenName`. [hadn't noticed this before]

2022-07-22 10:45 UTC, Vxatz commented on Pancakeswap-Agents/Large-LP-Token-Deposit-Withdraw/src/agent.spec.ts
> +      // Create test transaction with the deposit event
```suggestion
      // Create test transaction with the EmergencyWithdraw event
```

2022-07-22 10:45 UTC, Vxatz commented on Pancakeswap-Agents/Large-LP-Token-Deposit-Withdraw/src/agent.spec.ts
> +      // Create test transaction with the deposit event
```suggestion
      // Create test transaction with the EmergencyWithdraw event
```

2022-07-22 10:45 UTC, Vxatz commented on Pancakeswap-Agents/Large-LP-Token-Deposit-Withdraw/src/agent.spec.ts
> +      // Create test transaction with the deposit event
```suggestion
      // Create test transaction with the EmergencyWithdraw event
```

2022-07-22 10:45 UTC, Vxatz commented on Pancakeswap-Agents/Large-LP-Token-Deposit-Withdraw/src/agent.spec.ts
> +      // Create test transaction with the deposit event
```suggestion
      // Create test transaction with the EmergencyWithdraw event
```

2022-07-22 10:45 UTC, Vxatz commented on Pancakeswap-Agents/Large-LP-Token-Deposit-Withdraw/src/masterchef.fetcher.ts
> +    public async getLPToken(pid: string | number, block: string | number) {
```suggestion
    public async getLPToken(pid: BigNumber, block: string | number) {
```
That's the correct type, right?

2022-07-26 11:11 UTC, Vxatz approved these changes
Approving, as, besides the two small changes, everything else LGTM 🎉

2022-07-26 11:11 UTC, Vxatz commented on Pancakeswap-Agents/Large-LP-Token-Deposit-Withdraw/package.json
> +    "test": "jest",
```suggestion
    "test": "jest --detectOpenHandles",
```
Adding this because of the warning when running `npm test`

2022-07-26 11:11 UTC, Vxatz commented on Pancakeswap-Agents/Large-LP-Token-Deposit-Withdraw/package.json
> +    "@types/lru-cache": "^7.10.10",
Make sure to remove this as @0xtaf suggested and push the new package-lock

2022-08-03 08:36 UTC, 0xtaf approved these changes

2022-08-03 08:39 UTC, merged