@pancakeswap/large swap
NethermindEth/Forta-Agents pull request #298
Opened 2022-07-05 08:13 UTC by Olugbenga2000

# Bot name here

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [X] New Bot
- [ ] Fix a bot error
- [ ] Update a bot logic/test/documentation
- [ ] Code style update (formatting, renaming)
- [ ] Other (please describe):

## New Bot PR readiness

- [x] `npm install` command works (i.e. package-lock is updated properly)
- [x] The `name` and `description` fields of `package.json` describe the bot properly
- [x] All the libraries listed in `package.json` are being used
- [x] All the development libraries are in `devDependencies` section of `package.json`
- [x] The bot README is updated
- [x] The bot README sufficiently describes what the bot does
- [x] All the alerts that the bot emits are listed in the README
- [x] The txn/block examples listed in the README generate the expected findings
- [x] Code is easy to follow and/or properly commented
- [x] Bot contains tests
- [x] All tests pass when running `npm test`
- [x] Tests are not making real network calls (i.e. network interaction is properly mocked)
- [x] Tests cover all the paths (i.e. negative & positive test cases)
- [x] When the tests complete, no warning/errors are shown
- [x] `npm start` works without errors when executed using a jsonRpcUrl for each of the networks specified in the README
- [x] The networks specified in the README and the networks are listed in the `package.json` are the same
- [x] The code does what the README describes
- [ ] Network calls are properly being cached (if duplicated calls can occur)
- [x] A performance review has been done (e.g. `Promise.all` is used whenever possible)
- [x] The findings fields are filled out correctly
- [x] Findings `protocol` is specified (if the bot is for a specific one)
- [x] `metadata` of the findings contains all the information needed.
- [x] The SDK methods are being used appropriately (e.g. `filterLog`, `filterFunction`, `getEthersProvider`)
- [x] `ABI`s match the contracts used / `args` used from `LogDescriptions` exists in the `ABI`s
- [x] The bot follows Forta recommended [best practices](https://docs.forta.network/en/latest/best-practices/)
- [x] Bot can recover from failed error calls when they can fail (e.g. errors are being caught on calls that can fail)
- [x] `repository` is added in the `package.json`

## Comments (optional)

If there is some useful information or important note for reviewing/understanding this bot please describe it here.

2022-07-06 13:31 UTC, e1Ru1o requested changes

2022-07-06 13:31 UTC, e1Ru1o commented on PancakeSwap-Bots/Large-swap/src/utils.ts
> +  return [isValid, token0Address, token1Address];
this is not the best way of validating pairs, please use the `create2` approach.

2022-07-06 13:31 UTC, e1Ru1o commented on PancakeSwap-Bots/Large-swap/src/agent.ts
> +            const token1Balance = await getERC20Balance(token1Address, pairAddress, provider, txEvent.blockNumber - 1);
please pack this two call together in a `Promise.all`

2022-07-06 13:31 UTC, e1Ru1o commented on PancakeSwap-Bots/Large-swap/src/agent.ts
> +    }
remove the `console.log`, in fact this can be changed to:
```suggestion
    } catch { }
```

2022-07-06 13:31 UTC, e1Ru1o commented on PancakeSwap-Bots/Large-swap/src/agent.ts
> +    try {
the `try/catch` should be inside the map, not here. Even better will be to have it in the `isValidPancakePair` function so if something fails it returns `[false, "", ""]`

2022-07-06 13:31 UTC, e1Ru1o commented on PancakeSwap-Bots/Large-swap/src/agent.spec.ts
> +    expect(mockProvider.call).toHaveBeenCalledTimes(1);
this checks are not needed here.

2022-08-03 06:27 UTC, 0xtaf approved these changes
approving this, there's just one minor issue which is forta-agent is an older version rn.

2022-08-08 21:08 UTC, RCantu92 reviewed
Overall, mostly minor comments.

2022-08-08 21:10 UTC, RCantu92 requested changes
Requesting to move some functionality to its own dedicated fetcher file as well as a test file for the fetcher file.

2022-08-08 21:10 UTC, RCantu92 commented on PancakeSwap-Bots/Large-swap/src/utils.ts
> +const getERC20Balance = async (
I think for `isValidPancakePair`, and `getERC20Balance` we can create a fetcher file and its accompanying test file.

2022-08-09 07:42 UTC, Vxatz commented on PancakeSwap-Bots/Large-swap/README.md
> +- BSC
Changing it to "BNB Smart Chain":)

2022-08-09 13:44 UTC, Vxatz commented
- Fixed README issues
- Removed bignumber.js (losing precision in percentages now, but not a big deal I believe)
- Created fetcher class (For the testing part, I used real pairs as the `isValidPancakePair` method includes the create2 function)
- Moved the declaration of the mockProvider from `beforeEach` to `describe` (I had to remove the lines `expect(mockProvider.call).toHave...` because we would get wrong results now)
- Left the `if (amount0Out.gt(0)..` unchanged.

Let me know of any further changes.

2022-08-09 16:36 UTC, RCantu92 approved these changes
Mostly minor comments. Overall, LGTM. Approved. ✅

2022-08-09 16:36 UTC, RCantu92 commented on PancakeSwap-Bots/Large-swap/src/data.fetcher.spec.ts
> +describe("PancakeSwap pair fetcher test suite", () => {
```suggestion
describe("PancakeSwap Data Fetcher Test Suite", () => {
```
Small suggestion to since it is not only fetching the `pair`.

2022-08-09 16:36 UTC, RCantu92 commented on PancakeSwap-Bots/Large-swap/src/agent.spec.ts
> +  handleTransaction = provideBotHandler(TEST_LARGE_THRESHOLD, TEST_PANCAKE_FACTORY, mockFetcher, INIT_CODE);
```suggestion
  let handleTransaction: HandleTransaction = provideBotHandler(TEST_LARGE_THRESHOLD, TEST_PANCAKE_FACTORY, mockFetcher, INIT_CODE);
```
Could combine the above lines.

2022-08-09 21:42 UTC, Vxatz commented on PancakeSwap-Bots/Large-swap/README.md
> +- BNB Smart Chain
Of course!

2022-08-09 21:47 UTC, merged