Gmx7 (good one)
NethermindEth/Forta-Agents pull request #302
Opened 2022-07-14 21:44 UTC by ericmartihaynes

# Bot name here

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] New Bot
- [ ] Fix a bot error
- [ ] Update a bot logic/test/documentation
- [ ] Code style update (formatting, renaming)
- [ ] Other (please describe):

## New Bot PR readiness

- [ ] `npm install` command works (i.e. package-lock is updated properly)
- [ ] The `name` and `description` fields of `package.json` describe the bot properly
- [ ] All the libraries listed in `package.json` are being used
- [ ] All the development libraries are in `devDependencies` section of `package.json`
- [ ] The bot README is updated
- [ ] The bot README sufficiently describes what the bot does
- [ ] All the alerts that the bot emits are listed in the README
- [ ] The txn/block examples listed in the README generate the expected findings
- [ ] Code is easy to follow and/or properly commented
- [ ] Bot contains tests
- [ ] All tests pass when running `npm test`
- [ ] Tests are not making real network calls (i.e. network interaction is properly mocked)
- [ ] Tests cover all the paths (i.e. negative & positive test cases)
- [ ] When the tests complete, no warning/errors are shown
- [ ] `npm start` works without errors when executed using a jsonRpcUrl for each of the networks specified in the README
- [ ] The networks specified in the README and the networks are listed in the `package.json` are the same
- [ ] The code does what the README describes
- [ ] Network calls are properly being cached (if duplicated calls can occur)
- [ ] A performance review has been done (e.g. `Promise.all` is used whenever possible)
- [ ] The findings fields are filled out correctly
- [ ] Findings `protocol` is specified (if the bot is for a specific one)
- [ ] `metadata` of the findings contains all the information needed.
- [ ] The SDK methods are being used appropriately (e.g. `filterLog`, `filterFunction`, `getEthersProvider`)
- [ ] `ABI`s match the contracts used / `args` used from `LogDescriptions` exists in the `ABI`s
- [ ] The bot follows Forta recommended [best practices](https://docs.forta.network/en/latest/best-practices/)
- [ ] Bot can recover from failed error calls when they can fail (e.g. errors are being caught on calls that can fail)
- [ ] `repository` is added in the `package.json`

## Comments (optional)

If there is some useful information or important note for reviewing/understanding this bot please describe it here.

2022-07-14 21:50 UTC, ericmartihaynes commented
@0xtaf Here you go, sorry for the inconvenience. I don't know what happened but I got my fork all messed up and it seems it was adding all the changes from other bots. The way I fixed it I lost the git history, I hope it's not a huge deal. This bot is pretty similar to gmx5 so I made sure to implement all the changes I did for that bot after the review, so hopefully it does not need too many changes. I leave it in your hands 😀

2022-07-15 10:41 UTC, 0xtaf requested changes
nice work though it's a complicated one.

- Please just use the bot name as the folder name, so remove ‘gmx7-’ prefix.

- There are some moderate vulnerabilities in the packages. npm audit fix is needed.

- can you separate the agent configs from utils.ts to another file like agent.config.ts? this way it looks too complicated and readme says the ratio can be changed in utils.ts. so it’s better to have a separate config file to only make the config related changes for the related networks (arbitrum and avalanche).

2022-07-15 10:41 UTC, 0xtaf commented on GMX-Bots/gmx7-detect-profitable-trades/src/agent.ts
> +  priceFeeds.set("0xfea7a6a0b346362bf88a9e4a88416b77a57d6c2a", priceFeedData.mimPriceFeed); //MIM
these addresses are Arbitrum addresses. what happens in Avalanche network?

2022-07-15 10:41 UTC, 0xtaf commented on GMX-Bots/gmx7-detect-profitable-trades/src/utils.ts
> +  mimPriceFeed: new ethers.Contract("0x87121f6c9a9f6e90e59591e4cf4804873f54a95b", aggregatorV3InterfaceABI, provider),
these addresses are also Arbitrum addresses. is there a reason you didn't include Avalanche addresses given the network that the bot is running on?

2022-07-15 10:41 UTC, 0xtaf commented on GMX-Bots/gmx7-detect-profitable-trades/src/agent.spec.ts
> +import { createAddress, MockEthersProvider } from "forta-agent-tools/lib/tests";
```suggestion
import { createAddress } from "forta-agent-tools/lib/tests";
```

2022-07-15 10:41 UTC, 0xtaf commented on GMX-Bots/gmx7-detect-profitable-trades/src/agent.spec.ts
> +const aggregatorV3InterfaceABI = [
I think this can be imported from utils as they are the same.

2022-07-15 10:41 UTC, 0xtaf commented on GMX-Bots/gmx7-detect-profitable-trades/src/agent.spec.ts
> +describe("sandwich attack frontrun agent", () => {
description must be something else

2022-07-15 10:41 UTC, 0xtaf commented on GMX-Bots/gmx7-detect-profitable-trades/src/agent.spec.ts
> +  jest.setTimeout(25000);
why is this necessary?

2022-07-15 10:41 UTC, 0xtaf commented on GMX-Bots/gmx7-detect-profitable-trades/src/agent.spec.ts
> +  const mockTxEvent = createTransactionEvent({} as any);
this is not used

2022-07-15 10:41 UTC, 0xtaf commented on GMX-Bots/gmx7-detect-profitable-trades/src/agent.spec.ts
> +const init = initialize(getEthersProvider(), priceFeedData1);
this block seems unnecessary and not used since you mock prices with mockPriceFeed

2022-07-15 10:41 UTC, 0xtaf commented on GMX-Bots/gmx7-detect-profitable-trades/src/agent.spec.ts
> +    await init(); //run initialize before the tests
related to the comment above, this initialization is unnecessary because of mockPriceFeed

2022-07-15 10:41 UTC, 0xtaf commented on GMX-Bots/gmx7-detect-profitable-trades/src/agent.ts
> +let priceFeeds = new Map<string, ethers.Contract>([]);
```suggestion
const tradeHistory = new Map<string, [number, number, number]>([]);

const priceFeedCache = new Map<[string, number], number>([]);

const priceFeeds = new Map<string, ethers.Contract>([]);
```

2022-07-15 10:41 UTC, 0xtaf commented on GMX-Bots/gmx7-detect-profitable-trades/src/agent.ts
> +import { Finding, TransactionEvent, FindingSeverity, FindingType, ethers, getEthersProvider } from "forta-agent";
```suggestion
import { Finding, TransactionEvent, FindingSeverity, FindingType, ethers } from "forta-agent";
```

2022-07-28 15:40 UTC, RCantu92 requested changes
I think it's pretty important to update when we run the `expect` lines when checking multiple transactions.

2022-07-28 15:40 UTC, RCantu92 commented on GMX-Bots/gmx7-detect-profitable-trades/src/agent.spec.ts
> +    expect(findings).toStrictEqual([]);
```suggestion
    let findings = await handler(transaction);
    expect(findings).toStrictEqual([]);
    
    findings = await handler(transaction);
    expect(findings).toStrictEqual([]);
    
    findings = await handler(transaction);
    expect(findings).toStrictEqual([]);
```
Suggestion to test each individual call to the handler. Applicable in other unit tests as well.

2022-07-28 15:40 UTC, RCantu92 commented on GMX-Bots/gmx7-detect-profitable-trades/src/agent.spec.ts
> +    ]);
Similar to the other unit test, we should check with `expect().toStrictEqual()` in between the calls to the handler then `expect` an actual finding when it is supposed to be alerted.

For example
```
    let findings = await handler(transaction);
    expect(findings).toStrictEqual([]);

    findings = await handler(transaction);
    expect(findings).toStrictEqual([]);

    findings = await handler(transaction);
    expect(findings).toStrictEqual([
        Finding.fromObject({...});
    ]);

2022-07-29 07:22 UTC, Vxatz reviewed
- The tests are currently dependent on each other, and I believe that's wrong. For example, if you comment out the test at L80, then there are other tests failing

- Bot folder name needs to be changed

2022-07-29 18:56 UTC, 0xtaf commented
> * The tests are currently dependent on each other, and I believe that's wrong. For example, if you comment out the test at L80, then there are other tests failing
> * Bot folder name needs to be changed

that's right. I passed trade history as parameter now, so now I clear it in beforeEach. 
changed the folder name too.
thanks 👍

2022-07-29 18:57 UTC, 0xtaf commented
> I think it's pretty important to update when we run the `expect` lines when checking multiple transactions.

that's right. done 👍

2022-08-08 07:52 UTC, Vxatz requested changes

2022-08-08 07:52 UTC, Vxatz commented on GMX-Bots/Detect-profitable-trades/src/agent.spec.ts
> +  "event Swap(address account, address tokenIn, address tokenOut, uint256 amountIn, uint256 amountOut)",
```suggestion
  "event Swap(address account, address tokenIn, address tokenOut, uint256 amountIn, uint256 amountOut, uint256 amountOutAfterFees, uint256 feeBasisPoints)",
```

Updating the .spec's event signature as well

Edit: Also, we can remove either this or the `MOCK_SWAP_EVENT`, right?

2022-08-08 07:52 UTC, Vxatz commented on GMX-Bots/Detect-profitable-trades/README.md
> +  - Type is always set to "Medium"
```suggestion
  - Severity is always set to "Medium"
  - Type is always set to "Suspicious"
```

2022-08-08 07:52 UTC, Vxatz commented on GMX-Bots/Detect-profitable-trades/README.md
> +  - Metadata included:
```suggestion
  - Metadata contains:
```

2022-08-08 11:00 UTC, Vxatz approved these changes

2022-08-08 15:37 UTC, RCantu92 approved these changes
Approved ✅

2022-08-08 15:38 UTC, merged