UMA02 - Filled Relay
NethermindEth/Forta-Agents pull request #329
Opened 2022-08-29 22:27 UTC by RodrigoPina407

# uma-2

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] New Bot
- [ ] Fix a bot error
- [ ] Update a bot logic/test/documentation
- [ ] Code style update (formatting, renaming)
- [ ] Other (please describe):

## New Bot PR readiness

- [x] `npm install` command works (i.e. package-lock is updated properly)
- [x] The `name` and `description` fields of `package.json` describe the bot properly
- [x] All the libraries listed in `package.json` are being used
- [x] All the development libraries are in `devDependencies` section of `package.json`
- [x] The bot README is updated
- [x] The bot README sufficiently describes what the bot does
- [x] All the alerts that the bot emits are listed in the README
- [x] The txn/block examples listed in the README generate the expected findings
- [x] Code is easy to follow and/or properly commented
- [x] Bot contains tests
- [x] All tests pass when running `npm test`
- [x] Tests are not making real network calls (i.e. network interaction is properly mocked)
- [x] Tests cover all the paths (i.e. negative & positive test cases)
- [x] When the tests complete, no warning/errors are shown
- [x] `npm start` works without errors when executed using a jsonRpcUrl for each of the networks specified in the README
- [x] The networks specified in the README and the networks are listed in the `package.json` are the same
- [x] The code does what the README describes
- [x] Network calls are properly being cached (if duplicated calls can occur)
- [x] A performance review has been done (e.g. `Promise.all` is used whenever possible)
- [x] The findings fields are filled out correctly
- [x] Findings `protocol` is specified (if the bot is for a specific one)
- [x] `metadata` of the findings contains all the information needed.
- [x] The SDK methods are being used appropriately (e.g. `filterLog`, `filterFunction`, `getEthersProvider`)
- [x] `ABI`s match the contracts used / `args` used from `LogDescriptions` exists in the `ABI`s
- [x] The bot follows Forta recommended [best practices](https://docs.forta.network/en/latest/best-practices/)
- [x] Bot can recover from failed error calls when they can fail (e.g. errors are being caught on calls that can fail)
- [x] `repository` is added in the `package.json`

## Comments (optional)

If there is some useful information or important note for reviewing/understanding this bot please describe it here.

2022-08-30 07:41 UTC, 0xtaf requested changes
another great work 👍 the needed changes are minor and not logic related

2022-08-30 07:41 UTC, 0xtaf commented on UMA-Bots/Filled-Relay/README.md
> +(https://etherscan.io/tx/0xeffb7de17fe9ba78a4ea11803b4a2fce964261d3ecb800b0cad1935acb51e400): (expect 1 finding: 1 `FilledRelay` event)
this returns 2 findings

2022-08-30 07:41 UTC, 0xtaf commented on UMA-Bots/Filled-Relay/README.md
> +(https://arbiscan.io/tx/0xfcdb0e4614849710f2195d2eb2f9b3c9fa424b3e12066288c10b39bfa514b2ac): (expect 2 findings: 2 `FilledRelay` events)
these are the same tx hashes

2022-08-30 07:41 UTC, 0xtaf commented on UMA-Bots/Filled-Relay/src/agent.ts
> +let token_cache = new LRU<string, { tokenName: string; tokenDecimals: number }>({ max: 500 });
```suggestion
const token_cache = new LRU<string, { tokenName: string; tokenDecimals: number }>({ max: 500 });
```

2022-08-30 07:41 UTC, 0xtaf commented on UMA-Bots/Filled-Relay/src/agent.ts
> +      };
```suggestion
      const { amount, originChainId, destinationChainId, destinationToken, depositor, relayer, recipient, isSlowRelay } =
        filledRelayEvent.args;

      const tokenInfo: { tokenName: string; tokenDecimals: number } = await getTokenInfo(destinationToken, provider, token_cache, txEvent.blockNumber);

      const normalizedAmount = BN(amount.toString()).shiftedBy(-tokenInfo.tokenDecimals);

      const metadata = {
        amount: normalizedAmount.toString(10),
        originChainId: originChainId.toString(),
        destinationChainId: destinationChainId.toString(),
        tokenName: tokenInfo.tokenName,
        depositor,
        recipient,
        relayer,
      };
```

2022-08-31 15:01 UTC, Vxatz requested changes
Besides a few minor comments, LGTM 👍

2022-08-31 15:01 UTC, Vxatz commented on UMA-Bots/Filled-Relay/src/agent.spec.ts
> +  it("returns multiple finding if there are FilledRelay events emitted", async () => {
```suggestion
  it("returns multiple findings if there are FilledRelay events emitted", async () => {
```

2022-09-01 09:05 UTC, 0xtaf approved these changes
👍

2022-09-01 18:37 UTC, Vxatz approved these changes

2022-09-02 12:45 UTC, merged