@agent/curve finance suite
NethermindEth/Forta-Agents pull request #7
Opened 2021-09-10 19:50 UTC by rachit2501

2021-09-17 16:22 UTC, e1Ru1o requested changes
- Many agents are Function Calls detectors and I think that all of them are missing some calls (except for the one using the `general-agents-module`), please consider using the `general-agents-module` in all of them, and then add the missing cases in the tests.
- Many agents are Events detectors, please consider using the `general-agents-module` in all of them.
- Many of the test suits are named `high gas agent`
- The naming convention that we use in all the agents is the same of the `forta-examples` repo.  Instead of using spaces(`' '`), hyphens(`'-'`), underscores(`'_'`), camelCase, ...., we are using dots(`'.'`). Right now there are multiple patterns in the files, please use dots in everyone of them.

2021-09-17 16:22 UTC, e1Ru1o commented on Curve-finance-suite/src/tests/Curve-Dao-ClaimMany.spec.ts
> +describe("high gas agent", () => {
Change the `describe` name.

Also add more test, to check other cases returning 0 findings and cases when the function is called in internal txns

2021-09-22 11:12 UTC, rachit2501 commented on Curve-finance-suite/src/agents/Curve-Dao-ClaimMany.ts
> +    }
How to include the abi decode step? The general module export doesn't have that.

2021-09-22 23:51 UTC, e1Ru1o requested changes
The test for the functions call detectors agents, are not testing the cases where the call is internal call

2021-09-22 23:51 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/Curve-Dao-ClaimMany.ts
> +    }
```suggestion
```
This code is a duplicated check. The `FunctionCallsDetector` already check that and return findings only for the `claim_many` calls to the `to` address

2021-09-22 23:51 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/Curve-Gauge-SetRewards.ts
> +  };
The `FunctionCallsDetector` is not used in this handler, then the issue mentioned in the previous review is still unresolved

2021-09-22 23:51 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/crossAssetSwap.ts
> +    if (txEvent.addresses[address] == false) return findings;
```suggestion
    if (!txEvent.addresses[address]) return findings;
```

2021-09-22 23:51 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/addressProvider_Ownership_Transfer.ts
> +    if (txEvent.addresses[address] == false) return findings;
```suggestion
    if (!txEvent.addresses[address]) return findings;
```

2021-10-11 21:00 UTC, mauricio1802 requested changes

2021-10-15 16:04 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/cross.asset.swap.ts
> +    if (txEvent.addresses[address] == false) return findings;
Same as the previous suggestions
```suggestion
    if (!txEvent.addresses[address]) return findings;
```

2021-10-15 16:06 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/curve.dao.claim.many.ts
> +    description: 'Claim Rewards function called on pool',
on what pool? Is the address field in metadata the pool? Can you add the pool in the metadata? Can you add any metadata to make this finding more informative?

2021-10-15 16:09 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/curve.dao.claim.many.ts
> +
You can create the `agentHandler` outside the `TransactionHandler` in order to create it just one time
```suggestion
  const agentHandler = provideFunctionCallsDetectorAgent(
    createFindingGenerator(alertID),
    claimMany as any,
    { to: address },
  );
  return async (txEvent: TransactionEvent): Promise<Finding[]> => {
```

2021-10-15 16:11 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/curve.dao.claim.many.ts
> +    findings.push(createFinding(alertID));
why is this needed?

2021-10-15 16:12 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/curve.dao.create.lockevent.ts
> +    description: 'Create Lock Event funciton called on pool',
on what pool? Is the address field in metadata the pool? Can you add the pool in the metadata? Can you add any metadata to make this finding more informative?

2021-10-15 16:13 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/curve.dao.killing.gauge.ts
> +    description: "Set Killed funciton called on pool",
on what pool? Is the address field in metadata the pool? Can you add the pool in the metadata? Can you add any metadata to make this finding more informative?

2021-10-15 16:14 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/curve.gauge.set.rewards.ts
> +    description: "Set Rewards funciton called on pool",
on what pool? Is the address field in metadata the pool? Can you add the pool in the metadata? Can you add any metadata to make this finding more informative?

2021-10-15 16:14 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/deploy.metapool.ts
> +    description: "New meta pool is deployed",
Can you add any metadata to make this finding more informative?

2021-10-15 16:15 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/curve.dao.killing.gauge.ts
> +    if (txEvent.addresses[address] == false) return findings;
```suggestion
    if (!txEvent.addresses[address]) return findings;
```

2021-10-15 16:15 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/curve.dao.create.lockevent.ts
> +    if (txEvent.addresses[address] == false) return findings;
```suggestion
    if (!txEvent.addresses[address]) return findings;
```

2021-10-15 16:16 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/deploy.metapool.ts
> +    if (txEvent.addresses[address] == false) return findings;
```suggestion
    if (!txEvent.addresses[address]) return findings;
```

2021-10-15 16:16 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/kill.me.ts
> +    description: 'Kill Me funciton called on pool',
on what pool? Is the address field in metadata the pool? Can you add the pool in the metadata? Can you add any metadata to make this finding more informative?

2021-10-15 16:17 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/kill.me.ts
> +    if (txEvent.addresses[address] == false) return findings;
```suggestion
    if (!txEvent.addresses[address]) return findings;
```

2021-10-15 16:19 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/pool.migration.ts
> +    );
You can create the `agentHandler` outside the `TransactionHandler` in order to create it just one time
```suggestion
   const agentHandler = provideFunctionCallsDetectorAgent(
    createFindingGenerator(alertID),
    MIGRATE_POOL_SIG,
    { to: contractAddress },
  );
  return async (txEvent: TransactionEvent): Promise<Finding[]> => {
```

2021-10-15 16:21 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/ramp.ts
> +    description: 'Ramp Called',
Consider making this Finding more informative. The `name` field is not descriptive, maybe you can add Curve somewhere and also add the fee values in the metadata

2021-10-15 16:23 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/ramp.ts
> +  return async (TextEvent: TransactionEvent): Promise<Finding[]> => {
`TextEvent`?

2021-10-15 16:23 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/ramp.ts
> +    if (TextEvent.addresses[address] == false) return findings;
```suggestion
    if (`TextEvent.addresses[address]) return findings;
```

2021-10-15 16:25 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/registry.add.pool.ts
> +    description: "New Pool Added",
Can you add the pool in the metadata?

2021-10-15 16:25 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/registry.add.pool.ts
> +    if (TextEvent.addresses[address] == false) return findings;
```suggestion
    if (!TextEvent.addresses[address]) return findings;
```

2021-10-15 16:25 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/registry.add.pool.ts
> +  return async (TextEvent: TransactionEvent): Promise<Finding[]> => {
`TextEvent`?

2021-10-15 16:26 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/registry.remove.pool.ts
> +    description: "Pool Removed",
Can you add the pool in the metadata?

2021-10-15 16:27 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/registry.remove.pool.ts
> +    if (TextEvent.addresses[address] == false) return findings;
```suggestion
    if (!TextEvent.addresses[address]) return findings;
```

2021-10-15 16:27 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/registry.remove.pool.ts
> +  return async (TextEvent: TransactionEvent): Promise<Finding[]> => {
`TextEvent`?

2021-10-15 16:29 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/remove.imbalance.liquidity.ts
> +    description: 'RemoveLiquidityImbalance funciton called on pool',
on what pool? Is the address field in metadata the pool? Can you add the pool in the metadata? Can you add any metadata to make this finding more informative?

2021-10-15 16:47 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/remove.imbalance.liquidity.ts
> +    if (txEvent.addresses[address] == false) return findings;
```suggestion
    if (!txEvent.addresses[address]) return findings;
```

2021-10-15 16:48 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/stop.ramp.ts
> +    description: "Stop Ramp Called",
Please improve this finding information.

2021-10-15 16:48 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/stop.ramp.ts
> +  return async (TextEvent: TransactionEvent): Promise<Finding[]> => {
`TextEvent`?

2021-10-15 16:49 UTC, e1Ru1o commented on Curve-finance-suite/src/agents/stop.ramp.ts
> +    if (TextEvent.addresses[address] == false) return findings;
```suggestion
    if (!TextEvent.addresses[address]) return findings;
```

2021-11-23 23:10 UTC, mauricio1802 commented on Curve-finance-suite/src/tests/unkill.spec.ts
> +const ADDRESS = createAddress("11");
`createAddress` won't add the `0x` prefix for you, maybe you should add it. It would look like `createAddress("0x11")`

2021-11-23 23:13 UTC, mauricio1802 commented on Curve-finance-suite/src/agents/apply.newfee.ts
> +import {
You should update the name here or in the test file.

2021-11-23 23:19 UTC, mauricio1802 commented on Curve-finance-suite/src/tests/registry.remove.pool.spec.ts
> +const ADDRESS = '0X1111';
You should use `createAddress` here

2021-11-23 23:20 UTC, mauricio1802 commented on Curve-finance-suite/src/tests/registry.remove.pool.spec.ts
> +describe('Add Pool agent', () => {
Describe looks wrong. Should't be `Remove Pool`?

2021-12-03 15:43 UTC, RCantu92 commented on Curve-finance-suite/src/tests/pool.migration.spec.ts
> +const ADDRESS = '0X1111';
It is being used for the unit tests. However, did update to use new version `GAM`.

2021-12-10 21:55 UTC, closed without merging