Agent #9
NethermindEth/Forta-Agents pull request #75
Opened 2021-11-03 21:42 UTC by mauricio1802

2021-11-04 14:39 UTC, e1Ru1o requested changes

2021-11-04 14:39 UTC, e1Ru1o commented on Yearn-agents/ManagmentChanges/README.md
> +The test of this agent use a hardhat node forked from mainnet. For running test test you'll need to create a `.env` with the following format
```suggestion
The test of this agent use a hardhat node forked from mainnet. For running a test you'll need to create a `.env` with the following format
```

2021-11-04 14:39 UTC, e1Ru1o commented on Yearn-agents/ManagmentChanges/README.md
> +After setting this run the hardhat node using `npx hardhat node` and after that run `npm test`.
I think that you can add a command in the `package.json` for this, in order to use `npm run node` for example.

2021-11-04 14:39 UTC, e1Ru1o commented on Yearn-agents/ManagmentChanges/package.json
> +  "description": "Forta Agent Typescript starter project",
Update `name` & `description`

2021-11-05 16:41 UTC, e1Ru1o approved these changes

2021-11-10 17:41 UTC, rachit2501 approved these changes

2021-11-12 08:00 UTC, CeliktepeMurat reviewed
On the other hand, I assume that this agents also should detect `StrategyAdded` event. Shouldn't it?

2021-11-12 13:14 UTC, mauricio1802 commented on Yearn-agents/ManagmentChanges/src/agent.ts
> +    const yearnVaults: string[] = await getYearnVaults(etherProvider, txEvent.blockNumber);
Yes, I totally missed that 👍 .

2021-11-12 13:16 UTC, mauricio1802 commented
> On the other hand, I assume that this agents also should detect `StrategyAdded` event. Shouldn't it?

Yes, I missed it too :(.

2021-11-13 10:11 UTC, CeliktepeMurat approved these changes
LGTM

2021-11-22 11:57 UTC, merged