remove liquidity imbalance agent created from template
NethermindEth/Forta-Agents pull request #88
Opened 2021-12-06 16:40 UTC by yasmine9

Create remove liquidity imbalance agent using the  agent template. 
- Agent refactored using `GAM`. 
- Finding metadata improved. 
- More tests cases added.

2021-12-06 17:47 UTC, e1Ru1o requested changes

2021-12-06 17:47 UTC, e1Ru1o commented on Curve-finance-suite/Remove-Imbalace-Liquidity/package.json
> +  },
`forta-agent-tools` dependency is missing

2021-12-06 17:47 UTC, e1Ru1o commented on Curve-finance-suite/Remove-Imbalace-Liquidity/package.json
> +  "description": "Forta Agent Typescript starter project",
`name` needs to be changed to the agent id, you can choose one. We usually use `<protocol>-<agent#>` so `curve-2` will be fine.
Also add a small description of the agent in `description`

2021-12-06 17:47 UTC, e1Ru1o commented on Curve-finance-suite/Remove-Imbalace-Liquidity/src/agent.spec.ts
> +  });
If this will remains empty you can remove it

2021-12-07 16:04 UTC, mauricio1802 commented on Curve-finance-suite/Remove-Imbalace-Liquidity/src/agent.ts
> +    "CURVE-2",
Can we change this to use the numbers from the table at `https://www.notion.so/nethermind/CurveDAO-7807d9f852ac42f2973c5aa4747a80af`?

2021-12-07 16:24 UTC, e1Ru1o approved these changes

2021-12-07 17:28 UTC, mauricio1802 commented on Curve-finance-suite/Remove-Imbalace-Liquidity/src/agent.ts
> +export const CONTRACT_ADDRESS = '0xbEbc44782C7dB0a1A60Cb6fe97d0b483032FF1C7';
This is one specific pool, we may run this agent for more pools too.

2021-12-07 17:28 UTC, mauricio1802 commented on Curve-finance-suite/Remove-Imbalace-Liquidity/src/agent.ts
> +      type: FindingType.Info,
Maybe we can add `protocol: Curve Finance` here.

2021-12-08 20:09 UTC, mauricio1802 requested changes

2021-12-08 20:09 UTC, mauricio1802 commented on Curve-finance-suite/Remove-Imbalace-Liquidity/src/agent.ts
> +export const CONTRACT_ADDRESS = '0xbEbc44782C7dB0a1A60Cb6fe97d0b483032FF1C7';
Let's use a list of contract addresses here ( from `https://curve.readthedocs.io/ref-addresses.html#base-pools` for example) or specify in the `README` that this is only checking `StableSwap3Pool`.

2021-12-10 02:27 UTC, mauricio1802 approved these changes

2021-12-10 02:30 UTC, merged