Curve Pools events
NethermindEth/Forta-Agents pull request #94
Opened 2021-12-08 06:11 UTC by e1Ru1o

Detect `RampA` & `StopRampA` events

Remarks:
- Agent core improved
- Test Improved
- Findings Improved

2021-12-08 21:14 UTC, mauricio1802 requested changes

2021-12-08 21:14 UTC, mauricio1802 commented on Curve-finance-suite/Address-Provider-Ownership-Transfer/package-lock.json
> +{
I think this shouldn't be here

2021-12-08 21:14 UTC, mauricio1802 commented on Curve-finance-suite/Pools-RampA/src/agent.spec.ts
> +import { encodeParameters } from "nethermindeth-general-agents-module";
Shouldn't this be imported from `forta-agent-tools`?

2021-12-08 21:14 UTC, mauricio1802 commented on Curve-finance-suite/Pools-RampA/src/agent.spec.ts
> +  it("should ignore report the events in Pools", async () => {
I think this should be rephrased.

2021-12-10 20:51 UTC, e1Ru1o commented on Curve-finance-suite/Pools-RampA/package.json
> +    "@types/nodemon": "^1.19.0",
Used in one of the scripts, check `start:dev`

2021-12-10 21:17 UTC, mauricio1802 approved these changes

2021-12-10 21:19 UTC, RCantu92 approved these changes

2021-12-10 21:23 UTC, merged